<a href="https://colab.research.google.com/github/gubei528/Algorithm_Interview_Notes-Chinese/blob/master/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [4]:
B = torch.tensor((1,2,3),dtype = torch.float32,requires_grad=True)
B

tensor([1., 2., 3.], requires_grad=True)

In [5]:
Y  = B.pow(2).sum()
Y.backward()
B.grad

tensor([2., 4., 6.])

In [9]:
c = torch.Tensor(2,3)
c

tensor([[1.4281e+12, 3.0681e-41, 3.7835e-44],
        [0.0000e+00,        nan, 6.4460e-44]])

In [7]:
## 创建一个与B维度相同的全1张量
D = torch.ones_like(B)
D

tensor([1., 1., 1.])

torch.**_like() # 系列函数生成与指定张量维度相同的张量
1.   torch.ones_like() 生成全1张量
2.   torch.zeros_like() 生成全0张量
3.   torch.rand_like()  生成随机张量






In [10]:
torch.zeros_like(c)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [11]:
torch.rand_like(c)

tensor([[0.6545, 0.5184, 0.2010],
        [0.8323, 0.5884, 0.0642]])

针对创建好的张量，使用c.new_**()系列函数创建出新的张量


*   c.new_full((3,3),fill_value = *)  填充*的*3 x 3*的张量
*   c.new_zeros((3,3))   3x3 的全0张量
*   c.new_empty((3,3))   3x3 的空张量
*   c.new_ones((3,3))   3x3 全1张量





In [14]:
# 使用D.new_tensor()将列表转换成张量
e = [[1,2],[3,4]]  # list
e = c.new_tensor(e)
e.type

<function Tensor.type>

Tensor 和 numpy 数据转换
*  将numpy数组转换为torch张量，使用torch.as_tensor() 函数和torch.from_numpy()函
数
*  torch.numpy()函数转换为numpy数组
*  **注：numpy默认生成的数组为float64类型的**

In [15]:
import numpy as np


In [17]:
F = np.ones((3,3))
F_tensor = torch.as_tensor(F)
F_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [19]:
F_tensor2 = torch.from_numpy(F)
F_tensor2

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

生成随机数之前可以使用torch.manual_seed()函数，指定生成随机数种子，

In [20]:
torch.manual_seed(123)
A = torch.normal(mean = 0.0,std = torch.tensor(1.0))  # mean 指定随机数的均值，std参数指定随机数的标准差
# 若两个参数只有一个数，那么只会生成一个随机数，有多值的话，则会生成多个随机数
A

tensor(-0.1115)

In [23]:
torch.manual_seed(123)
A = torch.normal(mean = 0.0,std = torch.arange(1,10.0))
A 

tensor([-0.1115,  0.2407, -1.1089, -0.9617, -5.9846,  1.2556, -6.8065, -6.0404,
         2.9151])